import React, { useRef } from "react";
import "../assets/css/Auth/art_demo.css";
import Art from "../comp/Art";
function ArtDemo() {
  const Demo_arr = [
    {
      id: 1,
      name: "optional data",
      author: "shivdas",
      url_pic:
        "https://th.bing.com/th/id/OIP.IzXkIZzpcv_lDMB7MVoa3wHaG8?pid=ImgDet&w=184&h=172&c=7&dpr=1.4",
      description:
        "this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying details in the end tofhf  this woled",
      user: "admin",
      status: "accepted",
    },
    {
      id: 2,
      name: "optional data",
      author: "shivdas",
      url_pic:
        "https://th.bing.com/th/id/OIP._Eh-WTn7xA56woM5e91FgAHaHc?w=181&h=182&c=7&r=0&o=5&dpr=1.4&pid=1.7",
      description:
        "this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying details in the end tofhf  this woled",
      user: "admin",
      status: "accepted",
    },
    {
      id: 3,
      name: "optional data",
      author: "shivdas",
      url_pic:
        "https://th.bing.com/th/id/OIP.hV6hID63PHDxn7pyHrusNQHaFY?w=212&h=180&c=7&r=0&o=5&dpr=1.4&pid=1.7",
      description:
        "this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying details in the end tofhf  this woled",
      user: "admin",
      status: "accepted",
    },
    {
      id: 4,
      name: "optional data",
      author: "shivdas",
      url_pic: "",
      description:
        "this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying details in the end tofhf  this woled",
      user: "admin",
      status: "accepted",
    },
    {
      id: 5,
      name: "optional data",
      author: "shivdas",
      url_pic:
        "https://th.bing.com/th/id/OIP.9l8h5hQAwrPpxDPTtrjQ-gHaFX?w=231&h=180&c=7&r=0&o=5&dpr=1.4&pid=1.7",
      description:
        "this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying details in the end tofhf  this woled",
      user: "admin",
      status: "accepted",
    },
    {
      id: 6,
      name: "optional data",
      author: "shivdas",
      url_pic:
        "https://th.bing.com/th/id/OIP.s9BWa7vlt8CNk1LzHRFSDQHaEK?w=292&h=180&c=7&r=0&o=5&dpr=1.4&pid=1.7",
      description:
        "this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying this is random text generated by shivdas just to configure the verifying details in the end tofhf  this woled",
      user: "admin",
      status: "accepted",
    },
  ];
  const scrollContainer = useRef();
  return (
    <div id="art_demo">
      <h2 className="comp_title">Top Exhibits</h2>
      <button
        onClick={() => {
          let moveLeft = setInterval(() => {
            scrollContainer.current.scrollLeft += 1.5;
          }, 1);
          setTimeout(() => clearInterval(moveLeft), 1000);
        }}
        className="slide_btn"
        id="left_indicator"
      >
        &#8617;
      </button>
      <button
        onClick={() => {
          let moveLeft = setInterval(() => {
            scrollContainer.current.scrollLeft -= 1.5;
          }, 1);
          setTimeout(() => clearInterval(moveLeft), 1000);
        }}
        className="slide_btn"
        id="right_indicator"
      >
        &#8618;
      </button>
      <div id="art_container" ref={scrollContainer}>
        {Demo_arr.map((item) => {
          return (
            <div key={`${item.id}`}>
              <Art from="demo" data={item} />
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default ArtDemo;
